### ISSUE TITLE
UI looks bad in dark mode

### ISSUE THREAD

**Issue by chaseacton** [lionheart/TipJarViewController#10]
![IMG_1108](https://user-images.githubusercontent.com/3307194/69499463-37fee380-0ea7-11ea-8f65-5a350dd33fa5.PNG)

**Comment by henrik-dmg** [comment]
I have a branch ready to update this but sadly I can't push the repo

**Comment by dlo** [comment]
Hi @henrik-dmg, awesome! Could you submit a PR?

**Comment by henrik-dmg** [comment]
@dlo I would love to, but without a branch (which I can't push) I am unable to create PR

**Comment by dlo** [comment]
You should be able to create a fork of the repo on your own username and submit the PR from there. 🙂

**Comment by henrik-dmg** [comment]
I'd be super grateful if you could release a patch version including the new changes soon :)

**Comment by dlo** [comment]
@henrik-dmg Uploading version 2.1.0 to CocoaPods now. 🙂
