### ISSUE TITLE
Enhancement Request: Remove Subscription Requirement

### ISSUE THREAD

**Issue by zoopra9457** [lionheart/TipJarViewController#6]
My app continues to be rejected because of the following:

> App Store Information
> We were unable to find the following App Store Information items in App Store Connect.
> 
> – Information about the auto-renewable nature of the subscription in your app's description:
> • Title of publication or service
> • Length of subscription (time period and content or services provided during each subscription period)
> • Payment will be charged to iTunes Account at confirmation of purchase
> • Subscription automatically renews unless auto-renew is turned off at least 24-hours before the end of the current period
> • Account will be charged for renewal within 24-hours prior to the end of the current period, and identify the cost of the renewal
> • Subscriptions may be managed by the user and auto-renewal may be turned off by going to the user's Account Settings after purchase
> • Any unused portion of a free trial period, if offered, will be forfeited when the user purchases a subscription to that publication, where applicable
> ￼– A link to the terms of use in either the app description or EULA field
> ￼– A privacy policy link in the Privacy Policy URL field

I have provided them with a screen shot of the lower section of the app and they still are not approving the application.  Unless you can help me through this process, I'd like to remove the subscription tip because I really do not want to use it that feature.

I find it frustrating that they call this "metadata" because I don't think of this content as metadata but based on https://medium.com/revenuecat-blog/apple-will-reject-your-subscription-app-if-you-dont-include-this-disclosure-bba95244405d, the issue may be due to the above content being "below the fold".  

Thank you!

**Comment by dlo** [comment]
The solution is to include something like this at the bottom of your App Store description field. The following is for one of our apps, Health CSV Importer, but you can update the copy to fit your app and you should then be good to go. Let me know if you still run into an issue with App Review after making this change.

> Two optional, auto-renewing Tip Jar subscriptions are available for $0.49 per month or $4.99 per year (pricing varies by territory). Payments will be charged to your iTunes Account after confirmation. Subscriptions are automatically renewed unless auto-renew is turned off at least 24 hours before the end of the subscription period. Accounts will be charged for subscription renewals within 24 hours prior to the end of the current period. Subscriptions may be managed in your iTunes Account's Settings after purchasing.
> 
> Health CSV Importer's privacy policy: https://lionheartsw.com/software/health-csv-importer/privacy.html
> 
> Health CSV Importer's terms of use: https://lionheartsw.com/software/health-csv-importer/terms.html
